name: Go-new

on:
  schedule:
    - cron: '1 */8 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: |
          cd ./
          go get github.com/mitchellh/gox
          go get -v github.com/mattn/go-sqlite3
          CGO_ENABLED=1 gox -os "windows linux" -arch "amd64 arm arm64"
          ls
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: xdd_*
        ###tag: New
        tag_name: ${{ steps.tag.outputs.release_tag }}
        overwrite: true
        file_glob: true
